using UnityEngine;

/*
 *
 * THIS CLASS IS EMPTY FOR A REASON
 * IT IS USED JUST FOR COLLISION DETECTION OF RAYCAST OBJECTS
 * INTERACTABLE GAMEOBJECTS MUST HAVE ITEM SCRIPT FOR THE INTERACTIWITHOBJECTS SCRIPT TO WORK
 */
namespace UEFSimulator
{
    public class Item : MonoBehaviour { }
}